### ISSUE TITLE
tplink C7 c2 Aug-2017  can't install shadowsocks

### ISSUE THREAD

**Issue by trd168** [gwlim/Fast-Path-LEDE-OpenWRT#1]
i use Fast-Path-LEDE-OpenWRT/Fast-Path/Aug-2017/tplink C7 c2 firmware. 
i can install openconnect in this firmware.
but can't install shadowsocks-libev 

please help 
Thanks

**Comment by gwlim** [comment]
Post error message please.

**Comment by trd168** [comment]
Following is error message Thanks



Installing shadowsocks-libev (2.6.1-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.2/packages/mips_24kc/packages/shadowsocks-libev_2.6.1-1_mips_24kc.ipk


Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocks-libev:
 * 	kernel (= 4.4.71-1-840c23c3f9dc6160d8c7bd302c6f494d) * 	kernel (= 4.4.71-1-840c23c3f9dc6160d8c7bd302c6f494d) * 	kernel (= 4.4.71-1-840c23c3f9dc6160d8c7bd302c6f494d) * 
 * opkg_install_cmd: Cannot install package shadowsocks-libev.

**Comment by gwlim** [comment]
Try --nodeps

**Comment by juppin** [comment]
Which kmod package does it download for shadowsocks?

I could build an image with included kmod package...

**Comment by gwlim** [comment]
ShadowSocks is a network VPN application it has been included in the DEC 2018 built
