### ISSUE TITLE
ipset cannot be installed

### ISSUE THREAD

**Issue by kanchi233** [gwlim/Fast-Path-LEDE-OpenWRT#10]
At the beginning, I use the luci-app-shadowsocks_1.9.0-1 to configure shadowsocks, it need the dependency of ipset, but the ipset cannot be installed because of the kernel dependencies, so I use --nodeps to install it, but shadowsocks do not work.

After that I change the luci-app-shadowsocks-without-ipset_1.9.0-1 to configure it. It does not need the dependency of ipset, and finally shadowsocks works at all.

So can you give a  ipset package can be installed on this firmware? By the way I'm using the latest image you provide, Thx!!

**Comment by gwlim** [comment]
ipset included in later images
