### ISSUE TITLE
July 2018 build for Archer C7 v4?

### ISSUE THREAD

**Issue by maxspeed3006** [gwlim/Fast-Path-LEDE-OpenWRT#12]
Hi, noticed you updated several builds to july's snapshots but you didn't include one for the Archer C7 V4, i tried the previous one for this router (feb 2018) and it didn't work so i was eagerly waiting for an updated one.

**Comment by gwlim** [comment]
Hi @maxspeed3006 what was the issue with the previous build?
If it didn't work then I will not expect it to work now.
I don't have Archer C7v4 hardware so I will not know if it works.

**Comment by maxspeed3006** [comment]
Well, i only tried doing a sysupgrade once but it didn't work (wouldn't boot) so i ended up reflashing it back to regular OpenWRT, still, if you don't mind compiling a newer build i could test it out and report back if it works or not!

**Comment by maxspeed3006** [comment]
Hey, noticed you just uploaded the build for the Archer C7 v4, did a sysupgrade and been using it with no problems so far. Will report back in a few days to inform you if it's stable or not.

**Comment by maxspeed3006** [comment]
it's been stable for a few days now, so i'd say it's safe for anybody else to try it.

**Comment by gwlim** [comment]
Thanks for the feedback
