### ISSUE TITLE
July build for TP-Link WR1043NDv3?

### ISSUE THREAD

**Issue by akamizi** [gwlim/Fast-Path-LEDE-OpenWRT#13]
Hi, noticed you updated several builds to july's snapshots but you didn't include one for the TP-Link WR1043NDv3 as for previous build

Tnx for your job!

**Comment by akamizi** [comment]
I have a router version 1 and a version 3.
Both with your Lede version. Making the upgrade on v1 no problem, while with v3 I have this message (upgrade via web):
The uploaded image file does not contain a supported format. Make sure that you choose the generic image format for your platform.

**Comment by gwlim** [comment]
Can you try renaming the file name to a shorter name?

**Comment by akamizi** [comment]
ok work, only one thing (negligible):
in the system page

Model | TP-Link TL-WR1043N/ND v4
