### ISSUE TITLE
Crash and fall in boot loop with Aug 2018 build

### ISSUE THREAD

**Issue by bitching** [gwlim/Fast-Path-LEDE-OpenWRT#16]
Wdr4300 with Aug 2018 build.
When installing “ipset” with opkg, machine crashes immediately and fall in boot loop.
Can only reset the router in recovery mode.

Obviously i can not provide the logs because of the crash, still hope this can be solved.

**Comment by vinibali** [comment]
you can use the "logread -f" command in another session and provide some logs for troubleshooting.

**Comment by gwlim** [comment]
ipset is included in latest images
