### ISSUE TITLE
Mikrotik Routerboard RB450G

### ISSUE THREAD

**Issue by eisengrau** [gwlim/Fast-Path-LEDE-OpenWRT#17]
Hello,

Is it possible to release an image for this very popular, RB450G model? I am currently using your build on a WDR3600 which works very nicely, but I just received the above mentioned board, since I'm planning to upgrade to 500Mbps fiber soon. Thank you!

**Comment by gwlim** [comment]
Let me know if it works

**Comment by eisengrau** [comment]
It is working great, thank you very much indeed! :)

(The 'sign' is for bye-bye RouterOS forever! :) )

![img_20180905_165356](https://user-images.githubusercontent.com/42865787/45293559-cbddcd00-b4f8-11e8-9e75-3a14b58d9256.jpg)
