### ISSUE TITLE
Can I use MWAN3 on this firmware?

### ISSUE THREAD

**Issue by KatyushaScarlet** [gwlim/Fast-Path-LEDE-OpenWRT#19]
I saw that someone has solved the problem on LEDE.
https://github.com/coolsnowwolf/lede/commit/e6ef0d1d73a4b3d4feaae55c86d68474700526d1
Will you use this patch?

**Comment by KatyushaScarlet** [comment]
https://svn.dd-wrt.com/attachment/ticket/5986/linux-4.4-shortcut-fe-pbr-safe.patch

**Comment by gwlim** [comment]
Added a fix try https://github.com/gwlim/openwrt-sfe-flowoffload
