### ISSUE TITLE
Build for TL-WR1043N v5 ?

### ISSUE THREAD

**Issue by justinianpopa** [gwlim/Fast-Path-LEDE-OpenWRT#21]
Is there any chance you can add a build for TL-WR1043N v5 ? It seems to be documented here as a revision of TL-WR1043ND [https://openwrt.org/toh/tp-link/tl-wr1043nd](https://openwrt.org/toh/tp-link/tl-wr1043nd)

The only difference i can see is that from hw rev 5.x they changed the suffix from ND to just N, bumped up the clock speed a little and removed the USB port. Yet, there is a separate build of OpenWrt for the v5. Can i just use the v4.x build on a V5 without messing something up and needing to recover the hard way?

**Comment by gwlim** [comment]
Ok I saw the entry, will build next release.

**Comment by gwlim** [comment]
https://github.com/gwlim/openwrt-sfe-flowoffload
