### ISSUE TITLE
TP-Link WDR4300v1 two FW versions with "il" and without

### ISSUE THREAD

**Issue by DEX7777** [gwlim/Fast-Path-LEDE-OpenWRT#22]
Dear gwlim!
what the difference between TP-Link WDR4300v1-mips74k/ firmwares with  "il" and without?
does it support l2tp protocol?

![2018-10-09_15-36-57](https://user-images.githubusercontent.com/36702520/46669836-3b6ad900-cbd9-11e8-9fdf-2ea58b692abd.png)

**Comment by h7896v7347** [comment]
il - devices sold in Israel

https://www.mail-archive.com/openwrt-devel@lists.openwrt.org/msg17573.html

**Comment by gwlim** [comment]
@h7896v7347 is correct
