### ISSUE TITLE
Archer C7 v5

### ISSUE THREAD

**Issue by LinuxKernel1** [gwlim/Fast-Path-LEDE-OpenWRT#25]
Is it possible to add support?

v4:
[https://wikidevi.com/wiki/TP-LINK_Archer_C7_v4.x](url)
[https://openwrt.org/toh/hwdata/tp-link/tp-link_archer_c7_v4](url)

v5:
[https://wikidevi.com/wiki/TP-LINK_Archer_C7_v5.x](url)
[https://openwrt.org/toh/hwdata/tp-link/tp-link_archer_c7_v5](url)

Seems to be identical hardware.

**Comment by gwlim** [comment]
C7v4 already supported tested working by @maxspeed3006
https://github.com/gwlim/Fast-Path-LEDE-OpenWRT/tree/master/Fast-Path/Dec-2018/64MB%20And%20Above/TP-Link%20Archer%20C7v4-mips74k
C7v5 supported was added recently on trunk but I can only _try_ to build if someone could test.
Similar hardware but board_id, and gpio, partitioning might be different.

**Comment by LinuxKernel1** [comment]
I would like to test a build provided by you, but if you don't mind I would prefer to wait until you release builds for version 18.06.X or higher :-)

**Comment by gwlim** [comment]
Archer C7 v5 is uploaded
