### ISSUE TITLE
Add kernel dependencies

### ISSUE THREAD

**Issue by LinuxKernel1** [gwlim/Fast-Path-LEDE-OpenWRT#26]
There is a new package available in the master branch of openwrt: nft-qos

Can you please add the required kernel modules?

"DEPENDS:=+nftables +kmod-nft-netdev +kmod-nft-bridge"
([https://github.com/openwrt/packages/blob/master/net/nft-qos/Makefile](url))

**Comment by gwlim** [comment]
Next release I think, still trying to fine-tune the sizing removing the useless features without losing important features.

**Comment by gwlim** [comment]
https://github.com/gwlim/openwrt-sfe-flowoffload
