### ISSUE TITLE
Hi! Can you build for TP-Link WDR7500 v3 (Archer C7R WDR7500) ?

### ISSUE THREAD

**Issue by partizanosBY** [gwlim/Fast-Path-LEDE-OpenWRT#27]
Good day. Please build the firmware for this device (TP-Link WDR7500 v3)  with Fast Path support. 

https://openwrt.org/toh/tp-link/tl-wdr7500

Here are the firmware: 

http://downloads.openwrt.org/releases/18.06.1/targets/ar71xx/generic/openwrt-18.06.1-ar71xx-generic-tl-wdr7500-v3-squashfs-factory.bin
http://downloads.openwrt.org/releases/18.06.1/targets/ar71xx/generic/openwrt-18.06.1-ar71xx-generic-tl-wdr7500-v3-squashfs-sysupgrade.bin

THX!

**Comment by gwlim** [comment]
https://github.com/gwlim/openwrt-sfe-flowoffload
