### ISSUE TITLE
Is it enabled by default

### ISSUE THREAD

**Issue by Cereal-Killa** [gwlim/Fast-Path-LEDE-OpenWRT#28]
Not really an issue, just not sure if the optimization is enabled by default or if we need to change the firewall settings.
Thank you

![2018-12-14_15-53-17](https://user-images.githubusercontent.com/25939765/50019056-824dc400-ffb8-11e8-9829-85498b861b2e.png)

Model	TP-Link TL-WR1043N/ND v3
Processor	Qualcomm Atheros QCA9558 ver 1 rev 0
Architecture	MIPS 74Kc V5.0
Firmware Version	OpenWrt SFE r8609-d70ec3008d / LuCI ( Trunk )
Kernel Version	4.14.82

**Comment by gwlim** [comment]
It is not enabled by default
Please reference below:
https://github.com/gwlim/openwrt-sfe-flowoffload/issues/5
Also reference this issue to the correct repository here
Thanks.
