### ISSUE TITLE
Possibility of a fast path optimized build for the Archer C7 v4?

### ISSUE THREAD

**Issue by igr91** [gwlim/Fast-Path-LEDE-OpenWRT#5]
Hi. I love your builds, they've made wonders on both my 1043nd v1 and 1043nd v2. Would it be possible for you to make an optimized build for the C7 v4 when you update the rest? 

[C7 v2](https://wikidevi.com/wiki/TP-LINK_Archer_C7_v2.x) uses QCA9558 + QCA9880 + QCA8327
[C7 v4](https://wikidevi.com/wiki/TP-LINK_Archer_C7_v4.x) uses QCA9563 + QCA9880 + QCA8337

LEDE already supports this variant and the snapshots work fine as far as I can tell. Hardware on both revisions seems similar enough, so maybe selecting it in menuconfig results in a successful build? I'd be more than willing to test.

Thanks again for your hard work, it's amazing.

**Comment by gwlim** [comment]
Please know the recovery routine before trying this.
https://github.com/gwlim/Fast-Path-LEDE-OpenWRT/tree/master/Fast-Path/Dec-2017/TP-Link%20Archer%20C7v4%20Test
There is a lot of changes between stable and trunk, I backported the changes to build without error but there might be a chance I missed something.
I don't own the router and have no way to test

**Comment by igr91** [comment]
Just did a sysupgrade keeping settings over an old snapshot I was using before (r5296) and so far it works just fine, apart from the LEDs. Later in the day I'll do a reset and see if that gets them working.

Here's the kernel log
[kernel log c7 v4.txt](https://github.com/gwlim/Fast-Path-LEDE-OpenWRT/files/1525009/kernel.log.c7.v4.txt)


Thank you very much.

**Comment by gwlim** [comment]
Is the LED correct? If not I am going to assume it is and close this.
