### ISSUE TITLE
Possible to add MikroTik images?

### ISSUE THREAD

**Issue by ch6574** [gwlim/Fast-Path-LEDE-OpenWRT#8]
Hello,

Would it be possible to publish corresponding MikroTik images?

i.e. this, but with Fast Path: https://downloads.lede-project.org/snapshots/targets/ar71xx/mikrotik/openwrt-ar71xx-mikrotik-nand-large-squashfs-sysupgrade.bin

Thanks

**Comment by juppin** [comment]
You cloud use my build of this patch set... Image is a bit larger because of extroot packages, full dnsmasq and nano.

I had extra build mikrotik for you...

[My fork](https://github.com/juppin/Fast-Path-LEDE-OpenWRT/tree/master/Fast-Path/Mar-2018)

**Comment by ch6574** [comment]
Tried flashing it, but it gets stuck at "Decompressing Kernel..." when trying to boot.

```
RouterBOOT booter 6.41

RouterBoard 493G

CPU frequency: 680 MHz
  Memory size: 256 MiB
    NAND size: 128 MiB

Press any key within 2 seconds to enter setup..

loading kernel... OK
setting up elf image... OK
jumping to kernel code


OpenWrt kernel loader for AR7XXX/AR9XXX
Copyright (C) 2011 Gabor Juhos <juhosg@openwrt.org>
Decompressing kernel... 
```

Normally I get 

```
OpenWrt kernel loader for AR7XXX/AR9XXX
Copyright (C) 2011 Gabor Juhos <juhosg@openwrt.org>
Decompressing kernel... done!
Starting kernel at 80060000...

[    0.000000] Linux version 4.4.92 (buildbot@builds-02.infra.lede-project.org) (gcc version 5.4.0 (LEDE GCC 5.4.0 r3103-1b51a49) ) #0 Tue Oct 17 17:46:20 2017
[    0.000000] bootconsole [early0] enabled
```

Thanks anyway.

**Comment by juppin** [comment]
You could try to build it yourself with only shortcut-fe patch...

For 17.01: https://github.com/juppin/openwrt_custom_builds_17.01/blob/master/patches/666-shortcut-fe_17.01.patch

For trunk: https://github.com/juppin/openwrt_custom_builds_trunk/blob/master/patch/666-shortcut-fe_trunk.patch

Use it so:
cd openwrt
patch -p1 < ../666-shortcut-fe_XXX.patch
make menuconfig -> select shortcut-fe and fast-classifier

**Comment by eisengrau** [comment]
fyi, gwlim released an image for RB450G, see here: https://github.com/gwlim/Fast-Path-LEDE-OpenWRT/issues/17

**Comment by gwlim** [comment]
RB450G image added for mikrotik mips24k devices of different image size
