### ISSUE TITLE
Hello! Can you assemble the firmware for TP-LINK Archer C7 v1?

### ISSUE THREAD

**Issue by bardimnik** [gwlim/Fast-Path-LEDE-OpenWRT#9]
Hello! Can you assemble the firmware for TP-LINK Archer C7 v1?
I'm trying to assemble the firmware myself but I can not get it because of errors.
Help me please!!!

**Comment by juppin** [comment]
You cloud use my build of this patch set... Image is a bit larger because of extroot packages, full dnsmasq and nano.

[My fork](https://github.com/juppin/Fast-Path-LEDE-OpenWRT/tree/master/Fast-Path/Mar-2018)

**Comment by bardimnik** [comment]
Hello! I crossed the link and found what I wanted for a long time. Thank you very much for your work on this project. How can I thank you? I, for example, would like to make donate in your favor.

**Comment by juppin** [comment]
I had build it for my own mips74k router, so build a image for your router was very very simple.
I do not want a donation...
gwlim is the brain behind this patch set

Hope you have fun with your device :-)
